#!/usr/bin/env python3

"""
Copyright 2019 Matthew Powelson

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

'''
TODO:
    Future:
        Scale interactive marker based on size of ellipse
        Interactive_marker_utils process_feedback is specific to the ellipsoid.
        Add second layer of vertices scaled by some small amount to make it look nicer

Note:
    The stretching controls are in the mesh frame
    The 6 DOF control in in the parent frame
    When the 6 dof marker is moved, the mesh_link frame is updated to be on top of it.

'''

# Import ROS modules
import numpy as np
import rclpy
import tf2_py as tf2
import yaml
# Import pure Python modules
import sys
from ament_index_python.packages import get_package_share_directory
from geometry_msgs.msg import Vector3, Quaternion
from interactive_markers.interactive_marker_server import InteractiveMarkerServer
from rcl_interfaces.msg import ParameterDescriptor, ParameterType
from rclpy.node import Node, QoSProfile
from rclpy.time import Time
from tf2_ros import TransformBroadcaster, TransformListener, Buffer, TransformStamped
from tf_transformations import quaternion_matrix
from visualization_msgs.msg import InteractiveMarkerControl

# Import package modules
from interactive_geometry.ellipsoid_generator import EllipsoidGenerator
from interactive_geometry.interactive_marker_utils import InteractiveMarkerUtils
from interactive_geometry.mesh_exporter import MeshExporter
from interactive_geometry.utils import Marker, Point, to_triangle_marker_msg

A_PARAMETER = 'a'
B_PARAMETER = 'b'
C_PARAMETER = 'c'
TRANSLATION_PARAMETER = 'translation'
ROTATION_PARAMETER = 'rotation'
FILENAME_PARAMETER = 'filename'
NUM_PTS_PARAMETER = 'num_pts'
PARENT_LINK_PARAMETER = 'parent_link'
MESH_LINK_PARAMETER = 'mesh_link'


class InteractiveEllipsoid(Node):
    def __init__(self, **kwargs):
        super().__init__('interactive_ellipsoid_node', **kwargs)

        self.pub_marker = self.create_publisher(msg_type=Marker, topic='mesh_marker', qos_profile=QoSProfile(depth=10))

        # Read ROS parameters
        self.declare_parameter(A_PARAMETER, np.nan, ParameterDescriptor(type=ParameterType.PARAMETER_DOUBLE))
        self.declare_parameter(B_PARAMETER, np.nan, ParameterDescriptor(type=ParameterType.PARAMETER_DOUBLE))
        self.declare_parameter(C_PARAMETER, np.nan, ParameterDescriptor(type=ParameterType.PARAMETER_DOUBLE))
        self.declare_parameter(TRANSLATION_PARAMETER, [np.nan],
                               ParameterDescriptor(type=ParameterType.PARAMETER_DOUBLE_ARRAY))
        self.declare_parameter(ROTATION_PARAMETER, [np.nan],
                               ParameterDescriptor(type=ParameterType.PARAMETER_DOUBLE_ARRAY))
        self.declare_parameter(FILENAME_PARAMETER, rclpy.Parameter.Type.STRING)
        self.declare_parameter(NUM_PTS_PARAMETER, ParameterType.PARAMETER_INTEGER)
        self.declare_parameter(PARENT_LINK_PARAMETER, rclpy.Parameter.Type.STRING)
        self.declare_parameter(MESH_LINK_PARAMETER, rclpy.Parameter.Type.STRING)

        self.a_scale = self.get_parameter(A_PARAMETER).value
        self.b_scale = self.get_parameter(B_PARAMETER).value
        self.c_scale = self.get_parameter_or(C_PARAMETER).value
        trans = self.get_parameter(TRANSLATION_PARAMETER).value
        rot = self.get_parameter(ROTATION_PARAMETER).value
        self.filename = self.get_parameter(FILENAME_PARAMETER).value
        self.num_pts = self.get_parameter(NUM_PTS_PARAMETER).get_parameter_value().integer_value
        self.parent_link = self.get_parameter(PARENT_LINK_PARAMETER).value
        self.mesh_link = self.get_parameter(MESH_LINK_PARAMETER).value

        self.get_logger().info(f'Ellipsoid scaling is a: {self.a_scale}, b: {self.b_scale}, c: {self.c_scale}')
        self.get_logger().info(f'Initial transform between {self.parent_link} and {self.mesh_link} '
                               f'is translation: {trans}, rotation: {rot}')

        # Setup initial transform between the mesh_link and parent_link
        self.trans = Vector3()
        self.trans.x = trans[0]
        self.trans.y = trans[1]
        self.trans.z = trans[2]

        self.rot = Quaternion()
        self.rot.x = rot[0]
        self.rot.y = rot[1]
        self.rot.z = rot[2]
        self.rot.w = rot[3]

        # Set Marker server and TF
        self.server = InteractiveMarkerServer(self, "basic_controls")
        self.broadcaster = TransformBroadcaster(self)
        self.tf_buffer = Buffer()
        self.listener = TransformListener(self.tf_buffer, self)

        # Set up generation utilities
        self.util = InteractiveMarkerUtils(self, self.server, self.broadcaster, self.pub_marker)
        self.util.parent_link = self.parent_link
        self.util.mesh_link = self.mesh_link
        self.exporter = MeshExporter()

        # Make central control to move mesh
        position = Point()
        position.x = self.trans.x
        position.y = self.trans.y
        position.z = self.trans.z
        self.util.make6DofMarker(False, InteractiveMarkerControl.MOVE_3D, position, self.rot, True)
        self.server.applyChanges()

        # Make controls to resize mesh (positive direction)
        position = Point()
        position.x = self.a_scale
        position.y = 0.0
        position.z = 0.0
        self.util.makeMovingMarker(position, "a", axis=0)
        position = Point()
        position.x = 0.0
        position.y = self.b_scale
        position.z = 0.0
        self.util.makeMovingMarker(position, "b", axis=1)
        position = Point()
        position.x = 0.0
        position.y = 0.0
        position.z = self.c_scale
        self.util.makeMovingMarker(position, "c", axis=2)

        # Make controls to resize mesh (negative directon)
        position = Point()
        position.x = -1 * self.a_scale
        position.y = 0.0
        position.z = 0.0
        self.util.makeMovingMarker(position, "a_neg", axis=0)
        position = Point()
        position.x = 0.0
        position.y = 0.0
        position.z = -1 * self.c_scale
        self.util.makeMovingMarker(position, "c_neg", axis=2)

        # 'commit' changes and send to all clients
        self.server.applyChanges()

        # Generate the initial ellipsoid
        self.gen = EllipsoidGenerator(self.a_scale, self.b_scale, self.c_scale,
                                      self.num_pts)
        self.gen.generate_ellipsoid()

        self._timer = self.create_timer(1 / 30, self.update_mesh)

    def update_mesh(self):
        # Update the ellipsoid
        self.gen.update_ellipsoid(self.a_scale, self.b_scale, self.c_scale)

        marker = Marker()

        # Rebroadcast the tf
        try:
            tf_stamped_lookup_msg = self.tf_buffer.lookup_transform(target_frame=self.parent_link,
                                                                    source_frame=self.mesh_link,
                                                                    time=rclpy.time.Time())
            self.trans = tf_stamped_lookup_msg.transform.translation
            self.rot = tf_stamped_lookup_msg.transform.rotation
            tf_stamped_lookup_msg.header.stamp = self.get_clock().now().to_msg()
            tf_stamped_lookup_msg.header.frame_id = self.parent_link
            tf_stamped_lookup_msg.child_frame_id = self.mesh_link
            self.broadcaster.sendTransform(tf_stamped_lookup_msg)

            # Add/Update mesh
            marker = to_triangle_marker_msg(self.gen.vertices, self.gen.faces, self.mesh_link,
                                            self.get_clock().now().to_msg())
            marker.header.stamp = self.get_clock().now().to_msg()

            # Save mesh if button clicked
            if self.util.save_file:
                # Generate the transform matrix
                quaternion = [self.rot.x, self.rot.y, self.rot.z, self.rot.w]
                transformation_matrix = quaternion_matrix(quaternion)
                transformation_matrix[0, 3] = self.trans.x
                transformation_matrix[1, 3] = self.trans.y
                transformation_matrix[2, 3] = self.trans.z

                # Add a column of ones to the vertices - this makes the
                # dimensions match, and ensures the translation applies.
                extra_column = np.ones((self.gen.vertices.shape[0], 1))
                padded = np.append(self.gen.vertices, extra_column, 1)

                # Ordinarily, we would left-multiply the transform. However, the padded array
                # would need to be transposed, and then the result transposed again. We use the
                # identity (AB)T = (B)T(A)T to switch the order around and only transpose the transform
                transformed = np.matmul(padded.astype(float), np.transpose(transformation_matrix).astype(float))

                # Assign the transformed vertices (without padding) to the mesh
                self.gen.vertices = transformed[:, [0, 1, 2]]

                # Save/update ellipsoid parameters to yaml file
                package_share_directory = get_package_share_directory('interactive_geometry')
                yaml_filepath = package_share_directory + '/config/ellipsoid_params.yaml'
                with (open(yaml_filepath, 'w') as outfile):
                    yaml_input = data = {
                        "/**": {"ros__parameters": {'a': self.a_scale, 'b': self.b_scale, 'c': self.c_scale,
                                                    'translation': [self.trans.x, self.trans.y, self.trans.z],
                                                    'rotation': [self.rot.x, self.rot.y, self.rot.z, self.rot.w]}}
                    }
                    yaml.dump(data, outfile)

                self.get_logger().info(f'Updated ellipsoid scaling params are '
                                       f'a:{self.a_scale} b:{self.b_scale} c:{self.c_scale}')
                self.get_logger().info(f'Ellipsoid parameters saved to {yaml_filepath}')

                # Save to file
                self.exporter.mesh_to_stl(self.gen.vertices, self.gen.faces, self.filename)
                self.util.save_file = False
                self.get_logger().info('Exported mesh as ' + self.filename)

        except (tf2.LookupException, tf2.ConnectivityException, tf2.ExtrapolationException) as ex:
            tf_stamped_msg = TransformStamped()
            tf_stamped_msg.header.stamp = self.get_clock().now().to_msg()
            tf_stamped_msg.header.frame_id = self.parent_link
            tf_stamped_msg.child_frame_id = self.mesh_link
            tf_stamped_msg.transform.translation = self.trans
            tf_stamped_msg.transform.rotation = self.rot
            self.broadcaster.sendTransform(tf_stamped_msg)
            self.get_logger().error(f'{ex} Setting target frame to previous known transform.')

        # Publish the mesh
        self.pub_marker.publish(marker)


def main():
    rclpy.init(args=sys.argv)

    interactive_ellipsoid = InteractiveEllipsoid()
    rclpy.spin(interactive_ellipsoid)
    rclpy.shutdown()


if __name__ == '__main__':
    main()
