#!/usr/bin/env python3

"""
Copyright 2019 Matthew Powelson

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

'''
TODO:
    Future:
        Scale interactive marker based on size of ellipse
        Interactive_marker_utils process_feedback is specific to the ellipsoid.
        Add second layer of vertices scaled by some small amount to make it look nicer

Note:
    The stretching controls are in the mesh frame
    The 6 DOF control in in the parent frame
    When the 6 dof marker is moved, the mesh_link frame is updated to be on top of it.

'''

# Import ROS modules
import rclpy
from rclpy.node import Node
from rclpy.executors import ExternalShutdownException
from rclpy.time import Time
from visualization_msgs.msg import Marker
from geometry_msgs.msg import Point, Vector3, Quaternion
from interactive_markers.interactive_marker_server import *
from interactive_markers.menu_handler import *
from visualization_msgs.msg import InteractiveMarkerControl
from tf2_ros import TransformBroadcaster, TransformListener, Buffer, TransformStamped
import tf2_py as tf2
from tf_transformations import quaternion_matrix

# Import pure Python modules
import numpy as np
from ament_index_python.packages import get_package_share_directory

# Import package modules
from interactive_geometry.ellipsoid_generator import *
from interactive_geometry.mesh_exporter import *
from interactive_geometry.utils import *
from interactive_geometry.interactive_marker_utils import InteractiveMarkerUtils
import interactive_geometry.global_vars as global_vars

class InteractiveEllipsoid(Node):
    def __init__(self, **kwargs):
        super().__init__('interactive_ellipsoid_node', **kwargs)

        self.menu_handler = MenuHandler()
        self.pub_marker = self.create_publisher(msg_type=Marker, topic='mesh_marker', qos_profile=QoSProfile(depth=10))

        # Read ROS parameters
        global_vars.a_scale = self.get_parameter_or('~a',
                                                    rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.DOUBLE,
                                                                              1.0)).value
        global_vars.b_scale = self.get_parameter_or('~b',
                                                    rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.DOUBLE,
                                                                              1.0)).value
        global_vars.c_scale = self.get_parameter_or('~c',
                                                    rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.DOUBLE,
                                                                              1.0)).value
        package_share_directory = get_package_share_directory('interactive_geometry')
        self.filename = self.get_parameter_or('~filename',
                                              rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.STRING,
                                                                        package_share_directory + '/output.stl'))
        self.num_pts = self.get_parameter_or('~num_pts',
                                             rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.INTEGER,
                                                                       20))

        self.parent_link = self.get_parameter_or('~parent_link',
                                                 rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.STRING,
                                                                           'world'))
        self.mesh_link = self.get_parameter_or('~mesh_link',
                                               rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.STRING,
                                                                         'mesh_frame'))

        # Set Marker server and TF
        self.server = InteractiveMarkerServer(self, "basic_controls")
        self.broadcaster = TransformBroadcaster(self)
        self.tf_buffer = Buffer()
        self.listener = TransformListener(self.tf_buffer, self)

        # Set up generation utilities
        self.util = InteractiveMarkerUtils(self, self.server, self.broadcaster, self.pub_marker)
        self.util.parent_link = self.parent_link.value
        self.util.mesh_link = self.mesh_link.value
        self.exporter = MeshExporter()

        # Make central control to move mesh
        position = Point()
        position.x = 0.0
        position.y = 0.0
        position.z = 0.0
        self.util.make6DofMarker(False, InteractiveMarkerControl.MOVE_3D, position, True)
        self.server.applyChanges()

        # Make controls to resize mesh (positive direction)
        position = Point()
        position.x = float(global_vars.a_scale)
        position.y = 0.0
        position.z = 0.0
        self.util.makeMovingMarker(position, "a", axis=0)
        position = Point()
        position.x = 0.0
        position.y = float(global_vars.b_scale)
        position.z = 0.0
        self.util.makeMovingMarker(position, "b", axis=1)
        position = Point()
        position.x = 0.0
        position.y = 0.0
        position.z = float(global_vars.c_scale)
        self.util.makeMovingMarker(position, "c", axis=2)


        # Make controls to resize mesh (negative directon)
        position = Point()
        position.x = -1 * float(global_vars.a_scale)
        position.y = 0.0
        position.z = 0.0
        self.util.makeMovingMarker(position, "a_neg", axis=0)
        position = Point()
        position.x = 0.0
        position.y = 0.0
        position.z = -1 * float(global_vars.c_scale)
        self.util.makeMovingMarker(position, "c_neg", axis=2)

        # 'commit' changes and send to all clients
        self.server.applyChanges()

        # Generate the initial ellipsoid
        self.gen = EllipsoidGenerator(global_vars.a_scale, global_vars.b_scale, global_vars.c_scale,
                                      self.num_pts.value)
        self.gen.generate_ellipsoid()

        # Setup for loop
        self.trans = Vector3()
        self.trans.x = 0.0
        self.trans.y = 0.0
        self.trans.z = 0.0

        self.rot = Quaternion()
        self.rot.x = 0.0
        self.rot.y = 0.0
        self.rot.z = 0.0
        self.rot.w = 1.0

        tf_stamped_msg = TransformStamped()
        tf_stamped_msg.header.stamp = self.get_clock().now().to_msg()
        tf_stamped_msg.header.frame_id = self.parent_link.value
        tf_stamped_msg.child_frame_id = self.mesh_link.value
        tf_stamped_msg.transform.translation = self.trans
        tf_stamped_msg.transform.rotation = self.rot

        self.broadcaster.sendTransform(tf_stamped_msg)

        self._timer = self.create_timer(0.1, self.update_mesh)

    def update_mesh(self):
        # Update the ellipsoid
        self.gen.update_ellipsoid(global_vars.a_scale, global_vars.b_scale, global_vars.c_scale)

        # Rebroadcast the tf
        try:
            tf_stamped_lookup_msg = self.tf_buffer.lookup_transform(target_frame=self.parent_link.value,
                                                                    source_frame=self.mesh_link.value,
                                                                    time=rclpy.time.Time())
            self.trans = tf_stamped_lookup_msg.transform.translation
            self.rot = tf_stamped_lookup_msg.transform.rotation
            self.broadcaster.sendTransform(tf_stamped_lookup_msg)

        except (tf2.LookupException, tf2.ConnectivityException, tf2.ExtrapolationException):
            self.trans.x = 0.0
            self.trans.y = 0.0
            self.trans.z = 0.0

            self.rot.x = 0.0
            self.rot.y = 0.0
            self.rot.z = 0.0
            self.rot.w = 1.0
            tf_stamped_msg = TransformStamped()
            tf_stamped_msg.header.stamp = self.get_clock().now().to_msg()
            tf_stamped_msg.header.frame_id = self.mesh_link.value
            tf_stamped_msg.child_frame_id = self.parent_link.value
            tf_stamped_msg.transform.translation = self.trans
            tf_stamped_msg.transform.rotation = self.rot
            self.broadcaster.sendTransform(tf_stamped_msg)
            self.get_logger().info('Resetting TF')

        # Add/Update mesh
        marker = Marker()
        marker = to_triangle_marker_msg(self.gen.vertices, self.gen.faces, self.mesh_link.value,
                                        self.get_clock().now().to_msg())
        marker.header.stamp = self.get_clock().now().to_msg()

        # Save mesh if button clicked
        if self.util.save_file:
            # Generate the transform matrix
            quaternion = [self.rot.x, self.rot.y, self.rot.z, self.rot.w]
            transformation_matrix = quaternion_matrix(quaternion)
            transformation_matrix[3, 0] = self.trans.x
            transformation_matrix[3, 1] = self.trans.y
            transformation_matrix[3, 2] = self.trans.z

            # Add a column of ones to the vertices - this makes the
            # dimensions match, and ensures the translation applies.
            extra_column = np.ones((self.gen.vertices.shape[0], 1))
            padded = np.append(self.gen.vertices, extra_column, 1)

            # Ordinarily, we would left-multiply the transform. However, the padded array
            # would need to be transposed, and then the result transposed again. We use the
            # identity (AB)T = (B)T(A)T to switch the order around and only transpose the transform
            transformed = np.matmul(padded.astype(float), np.transpose(transformation_matrix).astype(float))

            # Assign the transformed vertices (without padding) to the mesh
            self.gen.vertices = transformed[:, [0, 1, 2]]

            # Save to file
            self.exporter.mesh_to_stl(self.gen.vertices, self.gen.faces, self.filename.value)
            self.util.save_file = False
            self.get_logger().info('Exported mesh as ' + self.filename.value)

        # Publish the mesh
        self.pub_marker.publish(marker)


def main():
    rclpy.init()
    try:
        rclpy.spin(InteractiveEllipsoid(), rclpy.executors.MultiThreadedExecutor())
    except (ExternalShutdownException, KeyboardInterrupt):
        pass
    finally:
        rclpy.try_shutdown()


if __name__ == '__main__':
    main()