#!/usr/bin/env python3

"""
Copyright 2019 Matthew Powelson

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

# Import ROS modules
import rclpy
from rclpy.node import Node
from rclpy import time, timer
from rclpy.executors import MultiThreadedExecutor
from visualization_msgs.msg import Marker
from geometry_msgs.msg import Point
from interactive_markers.interactive_marker_server import *
from interactive_markers.menu_handler import *
from visualization_msgs.msg import InteractiveMarkerControl
from tf2_ros import TransformBroadcaster, TransformListener, TransformStamped, Buffer, BufferClient
import tf2_py as tf2
from tf_transformations import quaternion_matrix

# Import pure Python modules
import numpy as np

# Import package modules
from interactive_geometry.ellipsoid_generator import *
from interactive_geometry.mesh_exporter import *
from interactive_geometry.utils import *
from interactive_geometry.interactive_marker_utils import  InteractiveMarkerUtils
import interactive_geometry.global_vars as global_vars

# Action interface
from rclpy.action import ActionServer
import interactive_geometry_msgs.msg
import interactive_geometry_msgs.action

menu_handler = MenuHandler()


class EllipsoidAction(Node):
    # create messages that are used to publish feedback/result
    _feedback = interactive_geometry_msgs.action.InteractiveEllipsoid.Feedback
    _result = interactive_geometry_msgs.action.InteractiveEllipsoid.Result

    def __init__(self, node_name):
        # Mesh publisher
        super().__init__(node_name)
        self._pub_marker = self.create_publisher(Marker, 'mesh_marker', 10)

        # Set Marker server and TF
        self._server = InteractiveMarkerServer("basic_controls", "")
        self._broadcaster = TransformBroadcaster(self)
        self.tf_buffer = Buffer()
        self._listener = TransformListener(self.tf_buffer, self)

        # Utilities class for manipulating interactive marker
        self._util = InteractiveMarkerUtils(self._server, self._broadcaster, self._pub_marker)

        # Setup action server
        self._action_name = node_name + "_action"
        self._as = ActionServer(node= node_name, action_type= interactive_geometry_msgs.action.InteractiveEllipsoid,
                                action_name=self._action_name, execute_callback= self.execute_cb)
        # self._as.start()

    def execute_cb(self, goal):

        # Read ROS parameters
        global_vars.a_scale = self.get_parameter_or('~a', rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.DOUBLE, 1.0))
        global_vars.b_scale = self.get_parameter_or('~b', rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.DOUBLE, 1.0))
        global_vars.c_scale = self.get_parameter_or('~c', rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.DOUBLE, 1.0))

        # Read goal from action
        filename = goal.results_directory + '/output.stl'
        num_pts = goal.num_pts
        parent_link = goal.parent_link
        mesh_link = goal.mesh_link

        # Set up generation utilities
        self._util.parent_link = parent_link
        self._util.mesh_link = mesh_link
        exporter = MeshExporter()

        # Make central control to move mesh
        position = Point()
        position.x = 0
        position.y = 0
        position.z = 0
        self._util.make6DofMarker(False, InteractiveMarkerControl.MOVE_3D, position, True)
        self._server.applyChanges()

        # Make controls to resize mesh (positive direction)
        position = Point()
        position.x = global_vars.a_scale
        position.y = 0
        position.z = 0
        self._util.makeMovingMarker( position, "a", axis=0)
        position = Point()
        position.x = 0
        position.y = global_vars.b_scale
        position.z = 0
        self._util.makeMovingMarker( position, "b", axis=1)
        position = Point()
        position.x = 0
        position.y = 0
        position.z = global_vars.c_scale
        self._util.makeMovingMarker( position, "c", axis=2)

        # Make controls to resize mesh (negative directon)
        position = Point()
        position.x = -1 * global_vars.a_scale
        position.y = 0
        position.z = 0
        self._util.makeMovingMarker( position, "a_neg", axis=0)
        position = Point()
        position.x = 0
        position.y = 0
        position.z = -1 * global_vars.c_scale
        self._util.makeMovingMarker( position, "c_neg", axis=2)

        # 'commit' changes and send to all clients
        self._server.applyChanges()

        # Generate the initial ellipsoid
        gen = EllipsoidGenerator(global_vars.a_scale, global_vars.b_scale, global_vars.c_scale, num_pts)
        gen.generate_ellipsoid()

        # Setup for loop
        trans = (0, 0, 0)
        rot = (0, 0, 0, 1.0)
        tf_stamped_msg = TransformStamped()
        tf_stamped_msg.header.stamp = self.get_clock().now().to_msg()
        tf_stamped_msg.header.frame_id = parent_link
        tf_stamped_msg.child_frame_id = mesh_link
        tf_stamped_msg.transform.translation = trans
        tf_stamped_msg.transform.rotation = rot

        self._broadcaster.sendTransform(tf_stamped_msg)
        rate = self.create_rate(30) # 30hz
        seq = 0
        finished = False
        while not finished:

            # Update the ellipsoid
            gen.update_ellipsoid(global_vars.a_scale, global_vars.b_scale, global_vars.c_scale)

            # Rebroadcast the tf
            try:
                tf_stamped_lookup_msg = TransformStamped()
                tf_stamped_lookup_msg = self.tf_buffer.lookupTransform(parent_link, mesh_link, rclpy.time.Time())
                trans = tf_stamped_lookup_msg.transform.translation
                rot = tf_stamped_lookup_msg.transform.rotation
                tf_stamped_msg = TransformStamped()
                tf_stamped_msg.header.stamp = self.get_clock().now().to_msg()
                tf_stamped_msg.header.frame_id = mesh_link
                tf_stamped_msg.child_frame_id = parent_link
                tf_stamped_msg.transform.translation = tf_stamped_lookup_msg.transform.translation
                tf_stamped_msg.transform.rotation = tf_stamped_lookup_msg.transform.rotation
                self._broadcaster.sendTransform(tf_stamped_msg)
            except (tf2.LookupException, tf2.ConnectivityException, tf2.ExtrapolationException):
                trans = (0, 0, 0)
                rot = (0, 0, 0, 1.0)
                tf_stamped_msg = TransformStamped()
                tf_stamped_msg.header.stamp = self.get_clock().now().to_msg()
                tf_stamped_msg.header.frame_id = mesh_link
                tf_stamped_msg.child_frame_id = parent_link
                tf_stamped_msg.transform.translation = trans
                tf_stamped_msg.transform.rotation = rot
                self._broadcaster.sendTransform(tf_stamped_msg)
                print("Resetting TF")
                continue

            # Add/Update mesh
            marker = Marker()
            marker = to_triangle_marker_msg(gen.vertices, gen.faces, mesh_link, seq, rclpy.time.Time())
            marker.header.stamp = rclpy.time.Time()

            # Save mesh if button clicked
            if self._util.save_file:
                # Generate the transform matrix
                transformation_matrix = quaternion_matrix(rot)
                transformation_matrix[3, 0] = trans.x
                transformation_matrix[3, 1] = trans.y
                transformation_matrix[3, 2] = trans.z

                # Add a column of ones to the vertices - this makes the
                # dimensions match, and ensures the translation applies.
                extra_column = np.ones((gen.vertices.shape[0],1))
                padded = np.append(gen.vertices, extra_column, 1)

                # Ordinarily, we would left-multiply the transform. However, the padded array
                # would need to be transposed, and then the result transposed again. We use the
                # identity (AB)T = (B)T(A)T to switch the order around and only transpose the transform
                transformed = np.matmul(padded.astype(float), np.transpose(transformation_matrix).astype(float))

                # Assign the transformed vertices (without padding) to the mesh
                gen.vertices = transformed[:,[0,1,2]]

                # Save to file
                exporter.mesh_to_stl(gen.vertices, gen.faces, filename)
                self._util.save_file = False
                print("Exported mesh as " + filename)
                self._result.results_path = filename
                self._result.success = True
                # self._as.set_succeeded(self._result)
                finished = True

            # Publish the mesh
            self._pub_marker.publish(marker)

        # Hide the controls, but leave the mesh showing
        self._server.clear()
        self._server.applyChanges()


if __name__ == '__main__':
    # Initialize node, publishers, and interactive marker server
    ellipsoid_node = rclpy.create_node('interactive_ellipsoid_node')
    executor = MultiThreadedExecutor()
    server = EllipsoidAction(ellipsoid_node.get_name())
    rclpy.spin(node=ellipsoid_node, executor=executor)

    ellipsoid_node.destroy_node()
    rclpy.shutdown()
