#!/usr/bin/env python3

"""
Copyright 2019 Matthew Powelson

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

'''
TODO:
    Future:
        Scale interactive marker based on size of ellipse
        Interactive_marker_utils process_feedback is specific to the ellipsoid.
        Add second layer of vertices scaled by some small amount to make it look nicer

Note:
    The stretching controls are in the mesh frame
    The 6 DOF control in in the parent frame
    When the 6 dof marker is moved, the mesh_link frame is updated to be on top of it.

'''

# Import ROS modules
import rclpy
from visualization_msgs.msg import Marker
from geometry_msgs.msg import Point, Vector3, Quaternion
from interactive_markers.interactive_marker_server import *
from interactive_markers.menu_handler import *
from visualization_msgs.msg import InteractiveMarkerControl
from tf2_ros import TransformBroadcaster, TransformListener, Buffer, TransformStamped
import tf2_py as tf2
from tf_transformations import quaternion_matrix

# Import pure Python modules
import numpy as np
from ament_index_python.packages import get_package_share_directory

# Import package modules
from interactive_geometry.ellipsoid_generator import *
from interactive_geometry.mesh_exporter import *
from interactive_geometry.utils import *
from interactive_geometry.interactive_marker_utils import InteractiveMarkerUtils
import interactive_geometry.global_vars as global_vars

menu_handler = MenuHandler()

if __name__ == '__main__':
    # Initialize node, publishers, and interactive marker server
    rclpy.init()
    node = rclpy.create_node('interactive_ellipsoid_node')
    pub_marker = node.create_publisher(msg_type=Marker, topic='mesh_marker', qos_profile=10)

    # Read ROS parameters
    global_vars.a_scale = node.get_parameter_or('~a',
                                                rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.DOUBLE,
                                                                          1.0))
    global_vars.b_scale = node.get_parameter_or('~b',
                                                rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.DOUBLE,
                                                                          1.0))
    global_vars.c_scale = node.get_parameter_or('~c',
                                                rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.DOUBLE,
                                                                          1.0))
    package_share_directory = get_package_share_directory('interactive_geometry')
    filename = node.get_parameter_or('~filename', rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.STRING,
                                                                            package_share_directory + '/output.stl'))
    num_pts = node.get_parameter_or('~num_pts',
                                    rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.INTEGER,
                                                              20))

    parent_link = node.get_parameter_or('~parent_link',
                                        rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.STRING,
                                                                  'world'))
    mesh_link = node.get_parameter_or('~mesh_link',
                                      rclpy.parameter.Parameter('', rclpy.parameter.Parameter.Type.STRING,
                                                                'mesh_frame'))

    # Set Marker server and TF
    server = InteractiveMarkerServer(node, "basic_controls")
    broadcaster = TransformBroadcaster(node)
    tf_buffer = Buffer()
    listener = TransformListener(tf_buffer, node)

    # Set up generation utilities
    util = InteractiveMarkerUtils(node, server, broadcaster, pub_marker)
    util.parent_link = parent_link
    util.mesh_link = mesh_link
    exporter = MeshExporter()

    # Make central control to move mesh
    position = Point()
    position.x = 0.0
    position.y = 0.0
    position.z = 0.0
    util.make6DofMarker(False, InteractiveMarkerControl.MOVE_3D, position, True)
    server.applyChanges()

    # Make controls to resize mesh (positive direction)
    position = Point()
    position.x = float(global_vars.a_scale.value)
    position.y = 0.0
    position.z = 0.0
    util.makeMovingMarker(position, "a", axis=0)
    position = Point()
    position.x = 0.0
    position.y = float(global_vars.b_scale.value)
    position.z = 0.0
    util.makeMovingMarker(position, "b", axis=1)
    position = Point()
    position.x = 0.0
    position.y = 0.0
    position.z = float(global_vars.c_scale.value)
    util.makeMovingMarker(position, "c", axis=2)

    # Make controls to resize mesh (negative directon)
    position = Point()
    position.x = -1 * float(global_vars.a_scale.value)
    position.y = 0.0
    position.z = 0.0
    util.makeMovingMarker(position, "a_neg", axis=0)
    position = Point()
    position.x = 0.0
    position.y = 0.0
    position.z = -1 * float(global_vars.c_scale.value)
    util.makeMovingMarker(position, "c_neg", axis=2)

    # 'commit' changes and send to all clients
    server.applyChanges()

    # Generate the initial ellipsoid
    gen = EllipsoidGenerator(global_vars.a_scale.value, global_vars.b_scale.value, global_vars.c_scale.value, num_pts.value)
    gen.generate_ellipsoid()

    # Setup for loop
    trans = Vector3()
    trans.x = 0.0
    trans.y = 0.0
    trans.z = 0.0

    rot = Quaternion()
    rot.x = 0.0
    rot.y = 0.0
    rot.z = 0.0
    rot.w = 1.0

    tf_stamped_msg = TransformStamped()
    tf_stamped_msg.header.stamp = node.get_clock().now().to_msg()
    tf_stamped_msg.header.frame_id = parent_link.value
    tf_stamped_msg.child_frame_id = mesh_link.value
    tf_stamped_msg.transform.translation = trans
    tf_stamped_msg.transform.rotation = rot

    broadcaster.sendTransform(tf_stamped_msg)
    rate = node.create_rate(30)  # 30hz
    seq = 0
    while rclpy.ok():

        # Update the ellipsoid
        gen.update_ellipsoid(global_vars.a_scale.value, global_vars.b_scale.value, global_vars.c_scale.value)

        # Rebroadcast the tf
        try:
            tf_stamped_lookup_msg = tf_buffer.lookup_transform(parent_link.value, mesh_link.value, node.get_clock().now())
            trans = tf_stamped_lookup_msg.transform.translation
            rot = tf_stamped_lookup_msg.transform.rotation
            tf_stamped_msg = TransformStamped()
            tf_stamped_msg.header.stamp = node.get_clock().now().to_msg()
            tf_stamped_msg.header.frame_id = mesh_link.value
            tf_stamped_msg.child_frame_id = parent_link.value
            tf_stamped_msg.transform.translation = tf_stamped_lookup_msg.transform.translation
            tf_stamped_msg.transform.rotation = tf_stamped_lookup_msg.transform.rotation
            broadcaster.sendTransform(tf_stamped_msg)
        except (tf2.LookupException, tf2.ConnectivityException, tf2.ExtrapolationException):
            trans = Vector3()
            trans.x = 0.0
            trans.y = 0.0
            trans.z = 0.0

            rot = Quaternion()
            rot.x = 0.0
            rot.y = 0.0
            rot.z = 0.0
            rot.w = 1.0
            tf_stamped_msg = TransformStamped()
            tf_stamped_msg.header.stamp = node.get_clock().now().to_msg()
            tf_stamped_msg.header.frame_id = mesh_link.value
            tf_stamped_msg.child_frame_id = parent_link.value
            tf_stamped_msg.transform.translation = trans
            tf_stamped_msg.transform.rotation = rot
            broadcaster.sendTransform(tf_stamped_msg)
            print("Resetting TF")
            continue

        # Add/Update mesh
        marker = Marker()
        marker = to_triangle_marker_msg(gen.vertices, gen.faces, mesh_link.value, seq, node.get_clock().now())
        marker.header.stamp = node.get_clock().now()

        # Save mesh if button clicked
        if util.save_file:
            # Generate the transform matrix
            transformation_matrix = quaternion_matrix(rot)
            transformation_matrix[3, 0] = trans.x
            transformation_matrix[3, 1] = trans.y
            transformation_matrix[3, 2] = trans.z

            # Add a column of ones to the vertices - this makes the
            # dimensions match, and ensures the translation applies.
            extra_column = np.ones((gen.vertices.shape[0], 1))
            padded = np.append(gen.vertices, extra_column, 1)

            # Ordinarily, we would left-multiply the transform. However, the padded array
            # would need to be transposed, and then the result transposed again. We use the
            # identity (AB)T = (B)T(A)T to switch the order around and only transpose the transform
            transformed = np.matmul(padded.astype(float), np.transpose(transformation_matrix).astype(float))

            # Assign the transformed vertices (without padding) to the mesh
            gen.vertices = transformed[:, [0, 1, 2]]

            # Save to file
            exporter.mesh_to_stl(gen.vertices, gen.faces, filename)
            util.save_file = False
            print("Exported mesh as " + filename)
            break;

        # Publish the mesh
        pub_marker.publish(marker)
        rate.sleep()
