<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>interactive_geometry_examples</name>
  <version>0.0.0</version>
  <description>The interactive_geometry_examples package</description>

  <maintainer email="david.spielman@swri.org">David Spielman</maintainer>
  <author email="mpowelson@todo.todo">Matthew Powelson</author>

  <license>Apache 2.0</license>

  <build_depend>interactive_geometry_msgs</build_depend>
  <build_depend>rclcpp</build_depend>
  <build_export_depend>interactive_geometry_msgs</build_export_depend>
  <build_export_depend>rclcpp</build_export_depend>
  <exec_depend>interactive_geometry_msgs</exec_depend>
  <exec_depend>rclcpp</exec_depend>
  <depend>rclcpp_actions</depend>
<!--  <depend>actionlib</depend>-->
<!--  <depend>roslib</depend>-->
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
